// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Immutable event log tracking every login attempt. Entries are never updated or deleted.
/// </summary>
public partial class LoginHistory
{
    public Guid Id { get; set; }

    /// <summary>
    /// The user who attempted to log in.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Authentication method: password, google, microsoft, github, magic_link, etc.
    /// </summary>
    public string LoginMethod { get; set; } = null!;

    /// <summary>
    /// Client IP address (IPv4 or IPv6) using PostgreSQL INET type.
    /// </summary>
    public IPAddress? IpAddress { get; set; }

    /// <summary>
    /// Browser or client user-agent string.
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>
    /// TRUE if login succeeded, FALSE if it failed.
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Reason for failure: invalid_password, account_locked, mfa_failed, etc. NULL on success.
    /// </summary>
    public string? FailureReason { get; set; }

    public DateTime CreatedAt { get; set; }
}