// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Fine-grained permissions: a specific action on a resource.
/// </summary>
public partial class Permission
{
    public Guid Id { get; set; }

    /// <summary>
    /// Unique permission key, e.g. &apos;workshop:read&apos;, &apos;invoice:write&apos;.
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// The resource being protected, e.g. &apos;workshop&apos;, &apos;vehicle&apos;, &apos;invoice&apos;.
    /// </summary>
    public string Resource { get; set; } = null!;

    /// <summary>
    /// The allowed operation, e.g. &apos;read&apos;, &apos;write&apos;, &apos;delete&apos;.
    /// </summary>
    public string Action { get; set; } = null!;

    /// <summary>
    /// &apos;platform&apos; = assignable only to global roles by platform_admin (e.g. tenants:*, subscription_plans:*, codebook:manage). &apos;tenant&apos; = assignable to any role.
    /// </summary>
    public string Scope { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}