// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Hashed refresh tokens for JWT session continuation. Immutable-style: created once, revoked at most once. The raw token is returned to the client only once and never persisted.
/// </summary>
public partial class RefreshToken
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    /// <summary>
    /// SHA-256 hash (Base64) of the raw refresh token. The raw value is never stored.
    /// </summary>
    public string TokenHash { get; set; } = null!;

    /// <summary>
    /// Absolute expiry of this refresh token.
    /// </summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// NULL = active. Set when the token is rotated, logged out, or revoked due to reuse / theft detection.
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// On rotation, points to the new token that superseded this one. Enables reuse detection.
    /// </summary>
    public Guid? ReplacedByTokenId { get; set; }

    public DateTime CreatedAt { get; set; }
}