// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Named roles that group permissions, assigned to users (e.g. admin, staff, customer_portal).
/// </summary>
public partial class Role
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}