// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// All principals that can authenticate: staff, admins, and future customer portal users.
/// </summary>
public partial class User
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Unique login identifier.
    /// </summary>
    public string Email { get; set; } = null!;

    /// <summary>
    /// Hashed password (bcrypt or Argon2). Never store plaintext. NULL for external auth (AD, Google, etc.).
    /// </summary>
    public string? PasswordHash { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    /// <summary>
    /// FK to tenant.tenants. NULL for platform-level super admins who are not bound to any tenant.
    /// </summary>
    public Guid? TenantId { get; set; }

    /// <summary>
    /// Active Directory objectGUID — immutable unique identifier. NULL for non-AD users.
    /// </summary>
    public Guid? AdObjectId { get; set; }

    /// <summary>
    /// Active Directory User Principal Name (e.g. jsmith@domain.local). Can change if user is renamed. NULL for non-AD users.
    /// </summary>
    public string? AdUpn { get; set; }

    /// <summary>
    /// Phone number for SMS-based MFA and user profile.
    /// </summary>
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// TRUE if two-factor authentication is active for this user.
    /// </summary>
    public bool MfaEnabled { get; set; }

    /// <summary>
    /// Active MFA method: totp, sms, or email. NULL if MFA not configured.
    /// </summary>
    public string? MfaMethod { get; set; }

    /// <summary>
    /// Encrypted TOTP shared secret for authenticator apps. Must be AES-256 encrypted at application level, never plaintext.
    /// </summary>
    public string? MfaSecret { get; set; }

    /// <summary>
    /// FALSE = account suspended (still exists, cannot log in).
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for bootstrap/seed records (self-referential).
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}