// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Workshop clients. Each customer belongs to exactly one tenant (workshop).
/// </summary>
public partial class Customer
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this customer belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    /// <summary>
    /// Optional link to auth.users. Set when the customer is granted portal access. UNIQUE — one auth account per customer.
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// Customer email address. Nullable — some customers may not have one.
    /// </summary>
    public string? Email { get; set; }

    public string? PhoneNumber { get; set; }

    public string? AddressLine1 { get; set; }

    public string? AddressLine2 { get; set; }

    public string? City { get; set; }

    public string? PostalCode { get; set; }

    public string? Country { get; set; }

    /// <summary>
    /// Internal workshop notes about this customer. Not visible to the customer.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// FALSE = customer record suspended / inactive.
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}