// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Vehicles owned by customers. tenant_id is denormalized for efficient plate/VIN lookups within a tenant.
/// </summary>
public partial class Vehicle
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The customer (owner) this vehicle belongs to.
    /// </summary>
    public Guid CustomerId { get; set; }

    /// <summary>
    /// Denormalized tenant scope. Must match customer.tenant_id — enforced by trigger tr_vehicles_tenant_check.
    /// </summary>
    public Guid TenantId { get; set; }

    public string Make { get; set; } = null!;

    public string Model { get; set; } = null!;

    public short? Year { get; set; }

    /// <summary>
    /// Vehicle Identification Number (17 characters).
    /// </summary>
    public string? Vin { get; set; }

    public string? LicensePlate { get; set; }

    public string? Color { get; set; }

    /// <summary>
    /// FK to codebook.fuel_types.
    /// </summary>
    public short? FuelTypeId { get; set; }

    public string? EngineType { get; set; }

    /// <summary>
    /// FK to codebook.transmissions.
    /// </summary>
    public short? TransmissionId { get; set; }

    /// <summary>
    /// Last recorded odometer reading.
    /// </summary>
    public int? Mileage { get; set; }

    /// <summary>
    /// Timestamp when the mileage value was last updated.
    /// </summary>
    public DateTime? MileageRecordedAt { get; set; }

    /// <summary>
    /// Internal workshop notes about this vehicle. Not visible to the customer.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}