// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Immutable audit log of all stock movements. Positive quantity = stock in, negative = stock out.
/// </summary>
public partial class StockTransaction
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this transaction belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// FK to warehouse.parts_catalog. The part being moved.
    /// </summary>
    public Guid CatalogPartId { get; set; }

    /// <summary>
    /// FK to codebook.stock_transaction_types (receipt, issue, return, adjustment_in, adjustment_out).
    /// </summary>
    public short TransactionTypeId { get; set; }

    /// <summary>
    /// Quantity moved. Positive for stock in (receipt, return, adjustment_in), negative for stock out (issue, adjustment_out). Cannot be zero.
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// FK to workshop.work_orders. Set when parts are issued to or returned from a work order. NULL otherwise.
    /// </summary>
    public Guid? WorkOrderId { get; set; }

    /// <summary>
    /// FK to workshop.suppliers. Set when parts are received from a supplier. NULL otherwise.
    /// </summary>
    public Guid? SupplierId { get; set; }

    /// <summary>
    /// Optional notes about this transaction (e.g. reason for adjustment).
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who performed this transaction.
    /// </summary>
    public Guid CreatedBy { get; set; }
}