// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Current inventory levels. One row per part per tenant. Updated atomically with each stock_transaction.
/// </summary>
public partial class Stock
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this stock belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// FK to warehouse.parts_catalog. The part being tracked.
    /// </summary>
    public Guid CatalogPartId { get; set; }

    /// <summary>
    /// Current quantity in stock. Must be &gt;= 0. Unit is defined by the part catalog entry.
    /// </summary>
    public decimal QuantityOnHand { get; set; }

    /// <summary>
    /// Physical location in the warehouse (e.g. &quot;A3-12&quot;, &quot;Shelf B&quot;). NULL if not tracked.
    /// </summary>
    public string? BinLocation { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }
}