// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Annual leave entitlements. One row per employee per leave type per year.
/// </summary>
public partial class LeaveBalance
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this balance belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The employee this balance applies to.
    /// </summary>
    public Guid EmployeeId { get; set; }

    /// <summary>
    /// FK to codebook.leave_types (vacation, sick, personal, etc.).
    /// </summary>
    public short LeaveTypeId { get; set; }

    /// <summary>
    /// Calendar year this balance applies to (e.g. 2026).
    /// </summary>
    public short Year { get; set; }

    /// <summary>
    /// Total days allocated for this year. Supports half-days (e.g. 20.5).
    /// </summary>
    public decimal TotalDays { get; set; }

    /// <summary>
    /// Days consumed so far. Updated when leave requests are approved. Supports half-days.
    /// </summary>
    public decimal UsedDays { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}