// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Single-use backup codes for MFA recovery. Generated in batches, each code can only be used once.
/// </summary>
public partial class MfaRecoveryCode
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    /// <summary>
    /// Hashed recovery code (like passwords — never store plaintext).
    /// </summary>
    public string CodeHash { get; set; } = null!;

    /// <summary>
    /// TRUE after the code has been consumed. Cannot be reused.
    /// </summary>
    public bool IsUsed { get; set; }

    /// <summary>
    /// Timestamp when the code was consumed. NULL if unused.
    /// </summary>
    public DateTime? UsedAt { get; set; }

    public DateTime CreatedAt { get; set; }
}