// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Billable subscription plans offered to tenants. Includes pricing, billing cadence, usage limits, and feature flags.
/// </summary>
public partial class SubscriptionPlan
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Stable machine-readable identifier, e.g. &apos;free&apos;, &apos;pro&apos;. Never changes — safe to use in code and APIs.
    /// </summary>
    public string Code { get; set; } = null!;

    /// <summary>
    /// Translated display names as JSONB, e.g. {&quot;en&quot;: &quot;Pro&quot;, &quot;sr&quot;: &quot;Pro&quot;}.
    /// </summary>
    public string Label { get; set; } = null!;

    /// <summary>
    /// Translated marketing/descriptive text as JSONB. NULL if no description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Plan price per billing period, in the currency referenced by currency_id. 0 = free.
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// FK to codebook.currencies. The currency the plan is billed in.
    /// </summary>
    public short CurrencyId { get; set; }

    /// <summary>
    /// FK to codebook.billing_periods. How often the plan is billed (monthly, yearly, one_time, ...).
    /// </summary>
    public short BillingPeriodId { get; set; }

    /// <summary>
    /// Number of free trial days granted to new tenants on this plan. 0 = no trial.
    /// </summary>
    public short TrialDays { get; set; }

    /// <summary>
    /// Maximum users per tenant. NULL = unlimited.
    /// </summary>
    public int? MaxUsers { get; set; }

    /// <summary>
    /// Maximum vehicles tracked per tenant. NULL = unlimited.
    /// </summary>
    public int? MaxVehicles { get; set; }

    /// <summary>
    /// Maximum work orders created per calendar month per tenant. NULL = unlimited.
    /// </summary>
    public int? MaxWorkOrdersPerMonth { get; set; }

    /// <summary>
    /// Maximum storage (attachments, etc.) per tenant in MB. NULL = unlimited.
    /// </summary>
    public int? MaxStorageMb { get; set; }

    /// <summary>
    /// Feature flags as JSONB, e.g. {&quot;api_access&quot;: true, &quot;advanced_reports&quot;: false}. Drives feature gating in the application.
    /// </summary>
    public string Features { get; set; } = null!;

    /// <summary>
    /// TRUE = visible in self-serve signup. FALSE = internal/custom plan, only assignable by platform_admin.
    /// </summary>
    public bool IsPublic { get; set; }

    /// <summary>
    /// Controls display order in pricing tables. Lower values appear first.
    /// </summary>
    public short SortOrder { get; set; }

    /// <summary>
    /// FALSE = retired plan. Existing tenants keep it; new tenants cannot select it.
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for bootstrap/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}