// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Operational expenses of the workshop. Each expense belongs to one tenant.
/// </summary>
public partial class Expense
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this expense belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// FK to codebook.expense_categories (e.g. rent, utilities, tools).
    /// </summary>
    public short ExpenseCategoryId { get; set; }

    /// <summary>
    /// Optional FK to workshop.suppliers. Set when the expense is from a known supplier.
    /// </summary>
    public Guid? SupplierId { get; set; }

    /// <summary>
    /// Optional FK to hr.employees. The employee who incurred or submitted the expense.
    /// </summary>
    public Guid? EmployeeId { get; set; }

    /// <summary>
    /// Short description of what the expense is for.
    /// </summary>
    public string Description { get; set; } = null!;

    /// <summary>
    /// Expense amount. Must be positive.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// The date the expense occurred.
    /// </summary>
    public DateOnly ExpenseDate { get; set; }

    /// <summary>
    /// Optional internal notes about this expense.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}