// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Customer invoices. Linked to an appointment for full service visits, or stand-alone for walk-in quick jobs.
/// </summary>
public partial class Invoice
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this invoice belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The customer being billed.
    /// </summary>
    public Guid CustomerId { get; set; }

    /// <summary>
    /// The vehicle that was serviced.
    /// </summary>
    public Guid VehicleId { get; set; }

    /// <summary>
    /// Optional link to appointment. NULL for walk-in quick jobs (e.g. bulb change).
    /// </summary>
    public Guid? AppointmentId { get; set; }

    /// <summary>
    /// FK to codebook.invoice_statuses (draft, issued, paid, cancelled).
    /// </summary>
    public short InvoiceStatusId { get; set; }

    /// <summary>
    /// Timestamp when the invoice was issued to the customer. NULL while draft.
    /// </summary>
    public DateTime? IssuedAt { get; set; }

    /// <summary>
    /// Timestamp when the invoice was paid. NULL until paid.
    /// </summary>
    public DateTime? PaidAt { get; set; }

    /// <summary>
    /// Internal notes about this invoice.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}