// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Work orders created after vehicle inspection. Multiple per appointment (different mechanics/jobs). Tracks status from pending_parts through completion.
/// </summary>
public partial class WorkOrder
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this work order belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The appointment this work order was created from. Multiple work orders can reference the same appointment.
    /// </summary>
    public Guid AppointmentId { get; set; }

    /// <summary>
    /// The mechanic/employee assigned to this work order.
    /// </summary>
    public Guid EmployeeId { get; set; }

    /// <summary>
    /// FK to codebook.work_order_statuses (pending_parts, ready, in_progress, completed, cancelled).
    /// </summary>
    public short WorkOrderStatusId { get; set; }

    /// <summary>
    /// Description of the work to be done on this order.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Timestamp when work actually started. NULL until in_progress.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Timestamp when work was completed. NULL until completed.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Internal notes about this work order.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}