// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Lookup table for tenant subscription tiers (e.g. free, trial, paid).
/// </summary>
public partial class SubscriptionPlan
{
    /// <summary>
    /// SMALLSERIAL primary key. Max 32,767 values — sufficient for a codebook.
    /// </summary>
    public short Id { get; set; }

    /// <summary>
    /// Stable machine-readable identifier, e.g. &apos;free&apos;. Never changes — safe to use in code and APIs.
    /// </summary>
    public string Code { get; set; } = null!;

    /// <summary>
    /// Translated display names as JSONB, e.g. {&quot;en&quot;: &quot;Free&quot;, &quot;hr&quot;: &quot;Besplatno&quot;}. Use COALESCE(label-&gt;&gt;lang, label-&gt;&gt;&apos;en&apos;) to fall back to English.
    /// </summary>
    public string Label { get; set; } = null!;

    /// <summary>
    /// Controls display order in dropdowns. Lower values appear first.
    /// </summary>
    public short SortOrder { get; set; }

    /// <summary>
    /// FALSE = hidden from UI but retained for historical records that reference it.
    /// </summary>
    public bool IsActive { get; set; }
}