// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Master catalog of parts a workshop stocks. Each part belongs to one tenant. Supports barcode scanning.
/// </summary>
public partial class PartsCatalog
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this part belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// Manufacturer or supplier part number. NULL if unknown.
    /// </summary>
    public string? PartNumber { get; set; }

    /// <summary>
    /// Human-readable part name (e.g. &quot;Oil filter for BMW 320d&quot;).
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// EAN/UPC or internal barcode. Unique per tenant. NULL if not barcoded.
    /// </summary>
    public string? Barcode { get; set; }

    /// <summary>
    /// Optional detailed description of the part.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// FK to codebook.units_of_measure (e.g. piece, liter, kg).
    /// </summary>
    public short UnitOfMeasureId { get; set; }

    /// <summary>
    /// Optional FK to workshop.suppliers. Preferred supplier for reordering.
    /// </summary>
    public Guid? DefaultSupplierId { get; set; }

    /// <summary>
    /// Default purchase price (what you pay the supplier). NULL if not yet known.
    /// </summary>
    public decimal? CostPrice { get; set; }

    /// <summary>
    /// Default selling price (what you charge the customer). NULL if not yet set.
    /// </summary>
    public decimal? SellingPrice { get; set; }

    /// <summary>
    /// Minimum stock threshold. When quantity_on_hand drops below this, trigger reorder alert.
    /// </summary>
    public decimal MinStockLevel { get; set; }

    /// <summary>
    /// FALSE = part discontinued / no longer stocked.
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}