// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Each row represents one workshop / organization (tenant) using the system.
/// </summary>
public partial class Tenant
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    /// <summary>
    /// URL-friendly unique identifier, e.g. &apos;workshop-kragujevac&apos;.
    /// </summary>
    public string Slug { get; set; } = null!;

    public string? ContactEmail { get; set; }

    public string? ContactPhone { get; set; }

    /// <summary>
    /// FK to codebook.subscription_plans. Current subscription tier.
    /// </summary>
    public short SubscriptionPlanId { get; set; }

    public string? AddressLine1 { get; set; }

    public string? AddressLine2 { get; set; }

    public string? City { get; set; }

    public string? PostalCode { get; set; }

    public string? Country { get; set; }

    /// <summary>
    /// FALSE = tenant suspended. Active users of this tenant cannot log in.
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}