// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Transactional email templates. Multi-language: subject and body stored as JSONB keyed by locale.
/// </summary>
public partial class EmailTemplate
{
    public Guid Id { get; set; }

    /// <summary>
    /// Stable machine-readable identifier (e.g. &apos;welcome&apos;, &apos;password_reset&apos;).
    /// </summary>
    public string Code { get; set; } = null!;

    /// <summary>
    /// Per-locale subject, e.g. {&quot;en&quot;:&quot;Welcome&quot;,&quot;sr&quot;:&quot;Dobrodošli&quot;}. Supports {{Placeholder}} substitution.
    /// </summary>
    public string Subject { get; set; } = null!;

    /// <summary>
    /// Per-locale plain-text body. Required (fallback when HTML not provided).
    /// </summary>
    public string BodyText { get; set; } = null!;

    /// <summary>
    /// Optional per-locale HTML body.
    /// </summary>
    public string? BodyHtml { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }
}