namespace WorkshopAdmin.SharedKernel.Persistence;

/// <summary>UUID v7 primary key, generated by the database (<c>uuidv7()</c> default).</summary>
public abstract class Entity
{
    public Guid Id { get; set; }
}

/// <summary>
/// Standard domain table shape: audit columns + soft delete (root CLAUDE.md conventions).
/// <see cref="AuditSaveChangesInterceptor"/> fills the audit values; a global query
/// filter hides soft-deleted rows.
/// </summary>
public abstract class AuditableEntity : Entity
{
    public DateTimeOffset CreatedAt { get; set; }
    public Guid? CreatedBy { get; set; }
    public DateTimeOffset? UpdatedAt { get; set; }
    public Guid? UpdatedBy { get; set; }
    public bool IsDeleted { get; set; }
}

/// <summary>
/// Immutable event-log table shape (login_history, stock_transactions): only creation
/// audit, no updates, no soft delete.
/// </summary>
public abstract class AppendOnlyEntity : Entity
{
    public DateTimeOffset CreatedAt { get; set; }
    public Guid? CreatedBy { get; set; }
}
