// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Workshop employees. Each employee belongs to one tenant and has exactly one login account.
/// </summary>
public partial class Employee
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this employee belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// Link to auth.users — every employee must have a login account. UNIQUE — one auth account per employee. Name, email, phone are on auth.users.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// FK to codebook.employment_types (salaried, hourly).
    /// </summary>
    public short EmploymentTypeId { get; set; }

    /// <summary>
    /// Date the employee started working.
    /// </summary>
    public DateOnly HireDate { get; set; }

    /// <summary>
    /// Date the employee left. NULL if still employed.
    /// </summary>
    public DateOnly? TerminationDate { get; set; }

    /// <summary>
    /// Hourly rate for hourly employees. NULL for salaried employees. Used for time entry cost calculations.
    /// </summary>
    public decimal? HourlyRate { get; set; }

    /// <summary>
    /// Internal HR notes about this employee. Not visible to the employee.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}