// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Individual leave/absence requests with approval workflow.
/// </summary>
public partial class LeaveRequest
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this request belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The employee requesting leave.
    /// </summary>
    public Guid EmployeeId { get; set; }

    /// <summary>
    /// FK to codebook.leave_types (vacation, sick, personal, etc.).
    /// </summary>
    public short LeaveTypeId { get; set; }

    /// <summary>
    /// FK to codebook.leave_statuses (pending, approved, rejected, cancelled).
    /// </summary>
    public short LeaveStatusId { get; set; }

    /// <summary>
    /// First day of the requested leave period.
    /// </summary>
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// Last day of the requested leave period (inclusive).
    /// </summary>
    public DateOnly EndDate { get; set; }

    /// <summary>
    /// Number of leave days requested. Supports half-days (e.g. 0.5 for a half-day).
    /// </summary>
    public decimal TotalDays { get; set; }

    /// <summary>
    /// Optional reason or details for the leave request.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Employee (manager) who approved or rejected the request. NULL while pending.
    /// </summary>
    public Guid? ReviewedBy { get; set; }

    /// <summary>
    /// Timestamp of the approval/rejection. NULL while pending.
    /// </summary>
    public DateTime? ReviewedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}