// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Employee clock-in/out records. Tracks daily work time per employee.
/// </summary>
public partial class TimeEntry
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this time entry belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The employee who clocked in.
    /// </summary>
    public Guid EmployeeId { get; set; }

    /// <summary>
    /// Timestamp when the employee clocked in.
    /// </summary>
    public DateTime ClockIn { get; set; }

    /// <summary>
    /// Timestamp when the employee clocked out. NULL if still clocked in.
    /// </summary>
    public DateTime? ClockOut { get; set; }

    /// <summary>
    /// Total break time in minutes during this entry. Default 0.
    /// </summary>
    public short BreakDurationMin { get; set; }

    /// <summary>
    /// Optional notes about the time entry (e.g. task description).
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}