// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Junction table linking appointments to known service types (e.g. oil change, timing belt). Acts as structured indicators alongside the free-text description.
/// </summary>
public partial class AppointmentService
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The appointment this service indicator belongs to.
    /// </summary>
    public Guid AppointmentId { get; set; }

    /// <summary>
    /// FK to codebook.service_types. One row per service type per appointment.
    /// </summary>
    public short ServiceTypeId { get; set; }

    /// <summary>
    /// Optional notes specific to this service (e.g. &quot;customer says brakes are squeaking&quot;).
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }
}