// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Service appointments. Created when a customer calls or walks in to schedule vehicle service.
/// </summary>
public partial class Appointment
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this appointment belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// The customer requesting service.
    /// </summary>
    public Guid CustomerId { get; set; }

    /// <summary>
    /// The vehicle to be serviced.
    /// </summary>
    public Guid VehicleId { get; set; }

    /// <summary>
    /// FK to codebook.appointment_statuses (scheduled, confirmed, completed, cancelled).
    /// </summary>
    public short AppointmentStatusId { get; set; }

    /// <summary>
    /// Date the customer would prefer. NULL if no preference.
    /// </summary>
    public DateOnly? PreferredDate { get; set; }

    /// <summary>
    /// Confirmed date/time. NULL until the workshop confirms a slot.
    /// </summary>
    public DateTime? ScheduledAt { get; set; }

    /// <summary>
    /// Free-text description of what the customer needs — written during intake (phone call or walk-in).
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Internal workshop notes about this appointment.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}