// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Individual line items on an invoice. Parts lines link to work_order_parts; labor lines link to work_orders. Walk-in invoice lines have no work order links.
/// </summary>
public partial class InvoiceLine
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The invoice this line belongs to.
    /// </summary>
    public Guid InvoiceId { get; set; }

    /// <summary>
    /// Optional link to the work order this line relates to. NULL for walk-in invoice lines.
    /// </summary>
    public Guid? WorkOrderId { get; set; }

    /// <summary>
    /// Optional link to the specific work_order_part. NULL for labor lines and walk-in lines.
    /// </summary>
    public Guid? WorkOrderPartId { get; set; }

    /// <summary>
    /// Line item description shown on the invoice (e.g. &quot;Oil filter OEM 123-456&quot; or &quot;Labor: brake pad replacement&quot;).
    /// </summary>
    public string Description { get; set; } = null!;

    /// <summary>
    /// Number of units. Supports decimals for labor hours (e.g. 1.5 hours).
    /// </summary>
    public decimal Quantity { get; set; }

    /// <summary>
    /// Price per unit.
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Percentage discount for this line item (0–100). Default 0 (no discount).
    /// </summary>
    public decimal DiscountPercent { get; set; }

    /// <summary>
    /// Total for this line (quantity * unit_price * (1 - discount_percent / 100)). Stored for immutability — once invoiced, the amount is fixed.
    /// </summary>
    public decimal LineTotal { get; set; }

    /// <summary>
    /// Optional notes for this line item.
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }
}