// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Parts suppliers. Each supplier belongs to one tenant. Contacts are stored in workshop.supplier_contacts.
/// </summary>
public partial class Supplier
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The tenant (workshop) this supplier belongs to.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// Supplier company name. Must be unique within the tenant.
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// General company email address.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// General company phone number.
    /// </summary>
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// Supplier address (free text).
    /// </summary>
    public string? Address { get; set; }

    /// <summary>
    /// Internal notes about this supplier.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// FALSE = supplier deactivated / no longer used.
    /// </summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}