// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Contact persons for a supplier. Multiple contacts per supplier, with optional primary flag. Tenant derived via supplier.
/// </summary>
public partial class SupplierContact
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The supplier this contact belongs to. Tenant is derived from the supplier row.
    /// </summary>
    public Guid SupplierId { get; set; }

    /// <summary>
    /// Contact first name.
    /// </summary>
    public string FirstName { get; set; } = null!;

    /// <summary>
    /// Contact last name.
    /// </summary>
    public string LastName { get; set; } = null!;

    /// <summary>
    /// Contact email address.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Contact phone number.
    /// </summary>
    public string? PhoneNumber { get; set; }

    /// <summary>
    /// TRUE = primary contact for this supplier. Enforced at application level (at most one per supplier).
    /// </summary>
    public bool IsPrimary { get; set; }

    /// <summary>
    /// Notes about this contact (e.g. role, availability).
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}