// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Parts needed for a work order. Tracks part details, supplier, availability status, and pricing.
/// </summary>
public partial class WorkOrderPart
{
    /// <summary>
    /// UUID v7 primary key (time-ordered).
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The work order this part belongs to.
    /// </summary>
    public Guid WorkOrderId { get; set; }

    /// <summary>
    /// FK to warehouse.parts_catalog. Set when part comes from warehouse stock. NULL if externally sourced.
    /// </summary>
    public Guid? CatalogPartId { get; set; }

    /// <summary>
    /// FK to workshop.suppliers. NULL if supplier not yet determined or part is from warehouse.
    /// </summary>
    public Guid? SupplierId { get; set; }

    /// <summary>
    /// FK to codebook.part_statuses (in_stock, ordered, received).
    /// </summary>
    public short PartStatusId { get; set; }

    /// <summary>
    /// Human-readable part name (e.g. &quot;Oil filter for BMW 320d&quot;).
    /// </summary>
    public string PartName { get; set; } = null!;

    /// <summary>
    /// Manufacturer or supplier part number. NULL if unknown.
    /// </summary>
    public string? PartNumber { get; set; }

    /// <summary>
    /// Number of units needed. Must be at least 1.
    /// </summary>
    public short Quantity { get; set; }

    /// <summary>
    /// Price per unit. NULL if not yet quoted.
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// Notes about this part (e.g. &quot;OEM only, no aftermarket&quot;).
    /// </summary>
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// User who created this record. NULL for system/seed records.
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// NULL on creation. Set on any update, including soft-delete.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// Soft delete flag. When TRUE, updated_at holds the deletion timestamp.
    /// </summary>
    public bool IsDeleted { get; set; }
}