// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkshopAdmin.Domain.Entities;

/// <summary>
/// Transactional email outbox. Append-only-style: rows are created in the business transaction; status, attempts, sent_at are updated by the dispatcher.
/// </summary>
public partial class EmailOutbox
{
    public Guid Id { get; set; }

    /// <summary>
    /// Tenant the email relates to. NULL for platform-level emails (e.g. tenant welcome).
    /// </summary>
    public Guid? TenantId { get; set; }

    public string ToAddress { get; set; } = null!;

    public string? ToName { get; set; }

    /// <summary>
    /// Rendered subject (template + placeholders applied at enqueue time).
    /// </summary>
    public string Subject { get; set; } = null!;

    /// <summary>
    /// Rendered plain-text body.
    /// </summary>
    public string BodyText { get; set; } = null!;

    /// <summary>
    /// Rendered HTML body (optional).
    /// </summary>
    public string? BodyHtml { get; set; }

    /// <summary>
    /// pending = awaiting dispatch; sending = claimed by dispatcher; sent = delivered to SMTP; failed = exceeded max_attempts.
    /// </summary>
    public string Status { get; set; } = null!;

    public int Attempts { get; set; }

    public int MaxAttempts { get; set; }

    public string? LastError { get; set; }

    /// <summary>
    /// When the dispatcher may next try this row. Increases exponentially after each failure.
    /// </summary>
    public DateTime NextAttemptAt { get; set; }

    public DateTime? SentAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid? CreatedBy { get; set; }
}